/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Taqseet;

import javax.swing.JTable;

/**
 *
 * @author ahmed
 */
public class deserve_money extends javax.swing.JPanel {

    /**
     * Creates new form recieved_items
     */
    public deserve_money() {
        initComponents();
        Home.styleTable(new JTable[]{stock_table3});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        stock_table3 = new javax.swing.JTable();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        excelStock2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(189, 195, 199));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 30, 60));

        jLabel76.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel76.setText("الكود : ");
        add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 75, 70, 60));

        jLabel79.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel79.setText("المسمي :");
        add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 75, 100, 60));

        jTextField29.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 60));

        jTextField28.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 120, 60));

        jLabel77.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel77.setText("اسم المندوب : ");
        add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 150, 60));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(153, 0, 0));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel78.setText("المندوب");
        add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 150, 60));

        jTextField30.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 160, 60));

        jLabel80.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("المبلغ :");
        add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 75, 80, 60));

        jLabel81.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel81.setText("التاريخ :");
        add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 90, 60));

        jTextField31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 270, 60));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        stock_table3.setAutoCreateRowSorter(true);
        stock_table3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stock_table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1", "1", "1"},
                {null, "1", "1", "1"},
                {null, "1", "1", "11"},
                {null, "11", "11", "11"},
                {null, "1", "1", "1"},
                {null, "11", "11", "1"},
                {null, "1", null, "1"},
                {null, "1", "1", "1"},
                {null, null, "1", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "التاريخ", "الكمية", "الصنف", "الكود"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stock_table3.setToolTipText("");
        stock_table3.setGridColor(new java.awt.Color(153, 153, 153));
        stock_table3.setRowHeight(45);
        stock_table3.setRowMargin(3);
        stock_table3.setShowHorizontalLines(true);
        stock_table3.setShowVerticalLines(true);
        stock_table3.setSurrendersFocusOnKeystroke(true);
        jScrollPane4.setViewportView(stock_table3);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1120, 510));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(153, 0, 0));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 60));

        jLabel84.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel84.setText("الإجمالي :");
        add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 100, 60));

        excelStock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel2.png"))); // NOI18N
        excelStock2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excelStock2MouseClicked(evt);
            }
        });
        add(excelStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void excelStock2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excelStock2MouseClicked
        Home.exportExcel(stock_table3, "جدول المبالغ المستحقة");
    }//GEN-LAST:event_excelStock2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel excelStock2;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTable stock_table3;
    // End of variables declaration//GEN-END:variables
}
