/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Taqseet;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class mandobMoney extends javax.swing.JPanel {

    /**
     * Creates new form recieved_items
     */
    public DefaultTableModel tah;
    static int cID = 0, type = 0;

    public mandobMoney(int id, String name) {
        initComponents();
        jLabel78.setText(name);
        cID = id;
        this.type = type;
        makeTable();
        mandobClientTable();
    }

    public void delTblCol(DefaultTableModel table) {
        if (table.getRowCount() != 0) {
            for (int i = table.getRowCount() - 1; i >= 0; i--) {
                table.removeRow(i);

            }
        }
    }

    DefaultTableModel createTableCols(JTable table, String[] cols) {
        DefaultTableModel dmodel;
        dmodel = (DefaultTableModel) table.getModel();
        for (int i = 0; i < cols.length; i++) {
            dmodel.addColumn(cols[i]);
        }
        return dmodel;
    }

    public void makeTable() {
        tah = createTableCols(money, new String[]{"التاريخ", "المبلغ ", "نوع العملية ", "اسم العميل"});
    }

    void mandobClientTable() {

        delTblCol(tah);
        DBcon d = new DBcon();
        String sql2 = "SELECT * FROM `mandobrecivables` , mandob , client WHERE mandobrecivables.mandobId = mandob.id AND mandobrecivables.clientId = client.id AND mandob.name = '" + jLabel78.getText() + "';";
        String clientName, type, val, date;
        try {
            d.rs = d.st.executeQuery(sql2);
            while ((d.rs).next()) {
                clientName = d.rs.getString("client.name");
                type = d.rs.getString("mandobrecivables.type");
                val = d.rs.getFloat("mandobrecivables.value") + "";
                date = "" + d.rs.getDate("mandobrecivables.date");
                String[] rowData = {date, val, type, clientName};
                tah.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري" + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        money = new javax.swing.JTable();
        jLabel83 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel82 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(189, 195, 199));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel77.setText("اسم المندوب : ");
        add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 150, 60));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(153, 0, 0));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel78.setText("المندوب");
        add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 310, 60));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        money.setAutoCreateRowSorter(true);
        money.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        money.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        money.setToolTipText("");
        money.setGridColor(new java.awt.Color(153, 153, 153));
        money.setRowHeight(45);
        money.setRowMargin(3);
        money.setShowHorizontalLines(true);
        money.setShowVerticalLines(true);
        money.setSurrendersFocusOnKeystroke(true);
        jScrollPane4.setViewportView(money);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1120, 570));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(153, 0, 0));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 240, 60));

        jButton1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jButton1.setText("تسليم مستحقات");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 60));

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel2.png"))); // NOI18N
        jLabel82.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel82MouseClicked(evt);
            }
        });
        add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        float x = 0;
        x = Float.valueOf(JOptionPane.showInputDialog("ادخل المبلغ المسلم", null));
        JOptionPane.showMessageDialog(null, x);

        DBcon d = new DBcon();
        try {
            float presentage = 0;
            d.rs = d.st.executeQuery("select * from mandob where id = '" + cID + "';");
            d.rs.last();
            float totalRicivedMony = d.rs.getFloat("total_recieved_money");
            float newRecived = -x + totalRicivedMony;
            d.st = d.con.createStatement();
            d.st.executeUpdate("UPDATE mandob set total_recieved_money = '" + newRecived + "' WHERE id = '" + cID + "';");
            d.st = d.con.createStatement();
            d.st.executeUpdate("INSERT INTO `mandobrecivables` (`id`, `mandobId`, `value`, `type`, `clientId`, `date`) VALUES (NULL, '" + cID + "', '" + x + "', 'تسليم مستحقات', '0', '" + LocalDate.now() + "');");

            d.st = d.con.createStatement();
            d.st.executeUpdate("INSERT INTO `history` (`id`, `person_id`, `person_type`, `date`, `operation`,type) VALUES (NULL, '" + cID + "', '" + this.jLabel78.getText() + "', '" + LocalDate.now() + "',  '" + x + "تسليم المندوب مبلغ قدره  ' , 'mandob');");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        mandobClientTable();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel82MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel82MouseClicked
        Home.exportExcel(money, "جدول مستحقات المندوب");
    }//GEN-LAST:event_jLabel82MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable money;
    // End of variables declaration//GEN-END:variables
}
