/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Taqseet;

import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class money extends javax.swing.JPanel {

    /**
     * Creates new form recieved_items
     */
    public money() {
        initComponents();
        tahselat();
    }

    void tahselat() {
        String sql2;
        float counter = 0;
        DBcon d = new DBcon();
        sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = false AND received_date between '" + LocalDate.now().getYear() + "-" + 1 + "-1' AND '" + LocalDate.now().getYear() + "-" + 12 + "-30';";
        try {
            d.rs = d.st.executeQuery(sql2);
            while ((d.rs).next()) {
                counter += d.rs.getFloat("value");
            }
            jLabel82.setText(String.valueOf(counter));
            counter = 0;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
        }
        sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND received_date between '" + LocalDate.now().getYear() + "-" + 1 + "-1' AND '" + LocalDate.now().getYear() + "-" + 12 + "-30';";
        try {
            d.rs = d.st.executeQuery(sql2);
            while ((d.rs).next()) {
                counter += d.rs.getFloat("value");
            }
            jLabel84.setText(String.valueOf(counter));
            counter = 0;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
        }
        sql2 = "SELECT * FROM `aqsat` WHERE received_date between '" + LocalDate.now().getYear() + "-" + 1 + "- 1' AND '" + LocalDate.now().getYear() + "-" + 12 + "-30';";
        try {
            d.rs = d.st.executeQuery(sql2);
            while ((d.rs).next()) {
                counter += d.rs.getFloat("value");
            }
            jLabel83.setText(String.valueOf(counter));
            counter = 0;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
        }

        sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + LocalDate.now().getYear() + "-" + 1 + "-1' AND '" + LocalDate.now().getYear() + "-" + 12 + "-30';";
        try {
            d.rs = d.st.executeQuery(sql2);
            while ((d.rs).next()) {
                counter += d.rs.getFloat("total_payment");
            }
            jLabel85.setText(String.valueOf(counter));
            counter = 0;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
        }

        sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + LocalDate.now().getYear() + "-" + 1 + "-1' AND '" + LocalDate.now().getYear() + "-" + 12 + "-30';";
        try {
            d.rs = d.st.executeQuery(sql2);
            while ((d.rs).next()) {
                counter += d.rs.getFloat("handOver");
            }
            jLabel88.setText(String.valueOf(counter));
            counter = 0;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(189, 195, 199));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 20, 560));

        jPanel2.setBackground(new java.awt.Color(189, 195, 199));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 380));

        jLabel79.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("اجمالي التحصيلات المتبقية");
        add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 340, 60));

        jLabel82.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(153, 0, 0));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("10000000");
        add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 300, 60));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(153, 0, 0));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("10000000");
        add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 300, 60));

        jLabel80.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("اجمالي التحصيلات الكلية");
        add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 300, 60));

        jLabel81.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("اجمالي التحصيلات المكتملة");
        add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 320, 60));

        jLabel84.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(153, 0, 0));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("10000000");
        add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 300, 60));

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الشهر", "يناير", "فبراير", "مارس", "ابريل", "مايو", "يونيو", "يوليو", "اغسطس", "سبتمبر", "اكتوبر", "نوفمبر", "ديسمبر" }));
        jComboBox1.setToolTipText("");
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 260, 60));

        jLabel85.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(153, 0, 0));
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setText("10000000");
        add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 300, 60));

        jLabel86.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("اجمالي بيع الكاش");
        add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 270, 60));

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "السنة", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));
        jComboBox2.setToolTipText("");
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 260, 60));

        jLabel87.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("المقدمات");
        add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 270, 60));

        jLabel88.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(153, 0, 0));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("10000000");
        add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 310, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().toString().equals("الشهر")) {
            tahselat();
        } else if (jComboBox1.getSelectedItem().toString().equals("يناير")) {
            JOptionPane.showMessageDialog(null, jComboBox2.getSelectedItem());
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = false AND month_payment = '" + 1 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 1 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 1 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = true AND month_payment = '" + 1 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 1 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 1 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 1 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 1 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 1 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 1 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 1 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 1 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 1 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("فبراير")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = false AND month_payment = '" + 2 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 2 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 2 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = true AND month_payment = '" + 2 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 2 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 2 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 2 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 2 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 2 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 2 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 2 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 2 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 2 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("مارس")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = false AND month_payment = '" + 3 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 3 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 3 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE   aqsat.done = true AND month_payment = '" + 3 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 3 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 3 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 3 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 3 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 3 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 3 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 3 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 3 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 3 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("ابريل")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE   aqsat.done = false AND month_payment = '" + 4 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 4 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 4 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = true AND month_payment = '" + 4 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 4 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 4 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 4 + "'  AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 4 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 4 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 4 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 4 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 4 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 4 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("مايو")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND month_payment = '" + 5 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 5 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 5 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE  aqsat.done = true AND month_payment = '" + 5 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 5 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 5 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 5 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 5 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 5 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 5 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 5 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 5 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 5 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("يونيو")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 6 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 6 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND month_payment = '" + 6 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 6 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 6 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 6 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 6 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 6 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 6 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 6 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 6 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 6 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("يوليو")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND month_payment = '" + 7 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 7 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 7 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND month_payment = '" + 7 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 7 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 7 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 7 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 7 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 7 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 7 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 7 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 7 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 7 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("اغسطس")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND month_payment = '" + 8 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 8 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 8 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND month_payment = '" + 8 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 8 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 8 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 8 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 8 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 8 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 8 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 8 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 8 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 8 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("سبتمبر")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND month_payment = '" + 9 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 9 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 9 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND month_payment = '" + 9 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 9 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 9 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 9 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 9 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 9 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 9 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 9 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 9 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 9 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("اكتوبر")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND month_payment = '" + 10 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 10 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 10 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND month_payment = '" + 10 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 10 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 10 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 10 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 10 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 10 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 10 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 10 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 10 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 10 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("نوفمبر")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND month_payment = '" + 11 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 11 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 11 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري" + ex);
            }
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND month_payment = '" + 11 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 11 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 1 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 11 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 11 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 11 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 11 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 11 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 11 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 11 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        } else if (jComboBox1.getSelectedItem().toString().equals("ديسمبر")) {
            String sql2;
            float counter = 0;
            DBcon d = new DBcon();
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = false AND month_payment = '" + 12 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 12 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 12 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel82.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE aqsat.done = true AND month_payment = '" + 12 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 12 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 12 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel84.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }
            sql2 = "SELECT * FROM `aqsat` WHERE month_payment = '" + 12 + "' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 12 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 12 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("value");
                }
                jLabel83.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE payment_type = 'كاش' AND received_date between '" + jComboBox2.getSelectedItem() + "-" + 12 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 12 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("total_payment");
                }
                jLabel85.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

            sql2 = "SELECT * FROM `client_recieved_items` WHERE received_date between '" + jComboBox2.getSelectedItem() + "-" + 12 + "-1' AND '" + jComboBox2.getSelectedItem() + "-" + 12 + "-30';";
            try {
                d.rs = d.st.executeQuery(sql2);
                while ((d.rs).next()) {
                    counter += d.rs.getFloat("handOver");
                }
                jLabel88.setText(String.valueOf(counter));
                counter = 0;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري");
            }

        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
