/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Taqseet;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ab o da
 */
public class multiMan extends javax.swing.JFrame {

    /**
     * Creates new form multiplePurchases
     */
    DefaultTableModel salesTable;

    public multiMan() {

        initComponents();
        salesTable = createTableCols(multiSalesTable, new String[]{"الاسم", "الكود"});
        Home.styleTable(new JTable[]{multiSalesTable});
    }

    String getUser() {
        String j = null;
        int x = 0;
        DBcon d = new DBcon();
        String sql = "SELECT User_name FROM users WHERE logged = 1";
        try {
            d.rs = d.st.executeQuery(sql);
            while (d.rs.next()) {
                x++;

            }
            if (x != 0) {
                d.rs = d.st.executeQuery(sql);
                while (d.rs.next()) {
                    j = d.rs.getString("User_name");
                }
            } else {
                j = "Hash";
            }
        } catch (SQLException ex) {
        }
        return j;
    }

    int auto_insert(String s, String s2) {
        int x = 0;
        DBcon d = new DBcon();
        String sql = "SELECT * FROM `" + s + "`";
        try {
            d.rs = d.st.executeQuery(sql);
            while ((d.rs).next()) {

                if ((d.rs.getInt(s2)) == x) {
                    x++;
                }
            }
        } catch (SQLException ex) {

        }
        return x;
    }

    DefaultTableModel createTableCols(JTable table, String[] cols) {
        DefaultTableModel dmodel;
        dmodel = (DefaultTableModel) table.getModel();
        for (int i = 0; i < cols.length; i++) {
            dmodel.addColumn(cols[i]);
        }
        return dmodel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multiSalesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        multiSalesTable = new javax.swing.JTable();
        manId = new javax.swing.JTextField();
        id_lbl = new javax.swing.JLabel();
        add_icon3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1194, 740));

        multiSalesPanel.setBackground(new java.awt.Color(113, 128, 147));
        multiSalesPanel.setPreferredSize(new java.awt.Dimension(1194, 800));
        multiSalesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        multiSalesTable.setAutoCreateRowSorter(true);
        multiSalesTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        multiSalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        multiSalesTable.setGridColor(new java.awt.Color(153, 153, 153));
        multiSalesTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        multiSalesTable.setRowHeight(45);
        multiSalesTable.setShowHorizontalLines(true);
        multiSalesTable.setShowVerticalLines(false);
        multiSalesTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                multiSalesTableKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(multiSalesTable);

        multiSalesPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 660, 540));

        manId.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        manId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manIdKeyPressed(evt);
            }
        });
        multiSalesPanel.add(manId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 470, 60));

        id_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        id_lbl.setForeground(new java.awt.Color(255, 255, 255));
        id_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        id_lbl.setText("الكود :");
        multiSalesPanel.add(id_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 80, 60));

        add_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addD.png"))); // NOI18N
        add_icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_icon3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_icon3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_icon3MouseExited(evt);
            }
        });
        multiSalesPanel.add(add_icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(multiSalesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(multiSalesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manIdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int id = 0;
            id = Integer.valueOf(manId.getText());
            String manName = null;
            DBcon d = new DBcon();
            String sql1 = "SELECT * FROM `mandob` WHERE mandob.id = '" + id + "';";
            try {
                d.rs = d.st.executeQuery(sql1);
                while ((d.rs).next()) {
                    manName = d.rs.getString("name");
                }
            } catch (SQLException ex) {

            }
            manId.setText(null);
            salesTable.addRow(new Object[]{
                manName,
                id,});
        }
    }//GEN-LAST:event_manIdKeyPressed

    private void multiSalesTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_multiSalesTableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int n = multiSalesTable.getSelectedRow();
            salesTable.removeRow(n);
  }    }//GEN-LAST:event_multiSalesTableKeyPressed

    private void add_icon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_icon3MouseClicked
        try {
            clientRI.Mman = new int[multiSalesTable.getRowCount()];

            for (int i = 0; i < multiSalesTable.getRowCount(); i++) {
                clientRI.Mman[i] = (int) multiSalesTable.getValueAt(i, 1);

            }
            JOptionPane.showMessageDialog(this, "<html><h1 style='font-family: Calibri; font-size:20px;'>تم </h3></html>");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><h1 style='font-family: Calibri; font-size:20px'>هناك خطأ ما -- حاول مرة اخري </h3></html>");
        }
    }//GEN-LAST:event_add_icon3MouseClicked

    private void add_icon3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_icon3MouseEntered

    }//GEN-LAST:event_add_icon3MouseEntered

    private void add_icon3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_icon3MouseExited
        add_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addD.png")));
    }//GEN-LAST:event_add_icon3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multiMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multiMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multiMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multiMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multiMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_icon3;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField manId;
    private javax.swing.JPanel multiSalesPanel;
    private javax.swing.JTable multiSalesTable;
    // End of variables declaration//GEN-END:variables

}
