/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Taqseet;

import Taqseet.DBcon;
import Taqseet.Home;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class recieved_money extends javax.swing.JPanel {

    /**
     * Creates new form recieved_items
     */
    public DefaultTableModel receivedMony;
    static int cID;

    public recieved_money() {
        initComponents();
        makeTable();
        mandobReceivedItemsTable();
        Home.styleTable(new JTable[]{recivedMonyT});
    }

    public recieved_money(int i, String name) {
        initComponents();
        cID = i;
        this.mandobName.setText(name);
        makeTable();
        mandobReceivedItemsTable();
        Home.styleTable(new JTable[]{recivedMonyT});
    }

    public void delTblCol(DefaultTableModel table) {
        if (table.getRowCount() != 0) {
            for (int i = table.getRowCount() - 1; i >= 0; i--) {
                table.removeRow(i);
            }
        }
    }

    int auto_insert(String s, String s2) {
        int x = 0;
        DBcon d = new DBcon();
        String sql = "SELECT * FROM `" + s + "`";
        try {
            d.rs = d.st.executeQuery(sql);
            while ((d.rs).next()) {

                if ((d.rs.getInt(s2)) == x) {
                    x++;
                }
            }
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري" );
        }
        return x;
    }

    DefaultTableModel createTableCols(JTable table, String[] cols) {
        DefaultTableModel dmodel;
        dmodel = (DefaultTableModel) table.getModel();
        for (int i = 0; i < cols.length; i++) {
            dmodel.addColumn(cols[i]);
        }
        return dmodel;
    }

    public void makeTable() {
        receivedMony = createTableCols(recivedMonyT, new String[]{"التاريخ", "المبلغ", "المسمى", "اسم العميل", "الكود"});
    }

    void mandobReceivedItemsTable() {
        delTblCol(receivedMony);
        DBcon d = new DBcon();
        String mandobName, id, title, date, value = null;
        try {
            d.rs = d.st.executeQuery("SELECT * FROM `received_money`, mandob WHERE received_money.mandob_id = mandob.id AND mandob.id = '" + cID + "';");
            while ((d.rs).next()) {
                mandobName = d.rs.getString("mandob.name");
                id = String.valueOf(d.rs.getInt("received_money.id"));
                title = String.valueOf(d.rs.getString("received_money.title"));
                date = String.valueOf(d.rs.getDate("received_money.date"));
                value = String.valueOf(d.rs.getFloat("received_money.value"));
                String[] rowData = {date, value, title, mandobName, id};
                receivedMony.addRow(rowData);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        val = new javax.swing.JTextField();
        mandobName = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        recivedMonyT = new javax.swing.JTable();
        jLabel82 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(189, 195, 199));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 30, 60));

        jLabel76.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel76.setText("الكود : ");
        add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 85, 70, 50));

        jLabel79.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel79.setText("المسمي :");
        add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 85, 100, 50));

        date.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 60));

        val.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        val.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        val.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valActionPerformed(evt);
            }
        });
        add(val, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 120, 60));

        mandobName.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        mandobName.setForeground(new java.awt.Color(153, 0, 0));
        mandobName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mandobName.setText("المندوب");
        add(mandobName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 360, 60));

        id.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 160, 60));

        jLabel80.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("المبلغ :");
        add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 85, 80, 50));

        jLabel81.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("استلام");
        add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 60, 50));

        name.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        name.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nameCaretUpdate(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 270, 60));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        recivedMonyT.setAutoCreateRowSorter(true);
        recivedMonyT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recivedMonyT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        recivedMonyT.setToolTipText("");
        recivedMonyT.setGridColor(new java.awt.Color(153, 153, 153));
        recivedMonyT.setRowHeight(45);
        recivedMonyT.setRowMargin(3);
        recivedMonyT.setShowHorizontalLines(true);
        recivedMonyT.setShowVerticalLines(true);
        recivedMonyT.setSurrendersFocusOnKeystroke(true);
        recivedMonyT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recivedMonyTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(recivedMonyT);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1140, 510));

        jLabel82.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel82.setText("اسم المندوب : ");
        add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/give_money.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/take_money.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel83.setText("التاريخ :");
        add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 85, 90, 50));

        jLabel84.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("تسليم");
        add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, 50));

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel2.png"))); // NOI18N
        jLabel87.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel87MouseClicked(evt);
            }
        });
        add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

        delTblCol(receivedMony);
        DBcon d = new DBcon();
        String mandobName, id, title, date, value = null;
        try {
            d.rs = d.st.executeQuery("SELECT * FROM `received_money`, mandob WHERE received_money.mandob_id = mandob.id AND mandob.id = '" + cID + "' AND received_money.title = '" + name.getText() + "';");
            while ((d.rs).next()) {
                mandobName = d.rs.getString("mandob.name");
                id = String.valueOf(d.rs.getInt("received_money.id"));
                title = String.valueOf(d.rs.getString("received_money.title"));
                date = String.valueOf(d.rs.getDate("received_money.date"));
                value = String.valueOf(d.rs.getFloat("received_money.value"));
                String[] rowData = {date, value, title, mandobName, id};
                receivedMony.addRow(rowData);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_nameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        DBcon d = new DBcon();
        try {
            d.con.createStatement();
            d.st.executeUpdate("INSERT INTO `received_money` (`id`, `mandob_id`, `title`, `date`, `value`) VALUES ('" + auto_insert("received_money", "id") + "', '" + cID + "',  '" + name.getText() + "', '" + LocalDate.now() + "','" + val.getText() + "');");
            float presentage = 0;
            d.rs = d.st.executeQuery("select * from mandob where id = '" + cID + "';");
            d.rs.last();
            float totalRicivedMony = d.rs.getFloat("total_recieved_money");
            float newRecived = -Float.valueOf(val.getText()) + totalRicivedMony;
//            d.st = d.con.createStatement();
//            d.st.executeUpdate("UPDATE mandob set total_recieved_money = '" + newRecived + "' WHERE id = '" + cID + "';");
            d.st = d.con.createStatement();
            d.st.executeUpdate("INSERT INTO `history` (`id`, `person_id`, `person_type`, `date`, `operation`,type) VALUES (NULL, '" + cID + "', '" + this.mandobName.getText() + "', '" + LocalDate.now() + "',  '" + val.getText() + "استلام من المندوب مبلغ قدره  ' , 'mandob');");
            JOptionPane.showMessageDialog(this, "<html><h1 style='font-family: Calibri; font-size:20px;'>تم </h3></html>");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><h1 style='font-family: Calibri; font-size:20px'>هناك خطأ ما -- حاول مرة اخري </h3></html>");
        }
        mandobReceivedItemsTable();

    }//GEN-LAST:event_jLabel1MouseClicked

    private void recivedMonyTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recivedMonyTMouseClicked
        int n = recivedMonyT.getSelectedRow();
        date.setText(receivedMony.getValueAt(n, 0).toString());
        val.setText(receivedMony.getValueAt(n, 1).toString());
        name.setText(receivedMony.getValueAt(n, 2).toString());
        id.setText(receivedMony.getValueAt(n, 4).toString());
    }//GEN-LAST:event_recivedMonyTMouseClicked

    private void nameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nameCaretUpdate
        delTblCol(receivedMony);
        DBcon d = new DBcon();
        String mandobName, id, title, date, value = null;
        try {
            d.rs = d.st.executeQuery("SELECT * FROM `received_money`, mandob WHERE received_money.mandob_id = mandob.id AND mandob.id = '" + cID + "' AND received_money.title like '" + name.getText() + "%';");
            while ((d.rs).next()) {
                mandobName = d.rs.getString("mandob.name");
                id = String.valueOf(d.rs.getInt("received_money.id"));
                title = String.valueOf(d.rs.getString("received_money.title"));
                date = String.valueOf(d.rs.getDate("received_money.date"));
                value = String.valueOf(d.rs.getFloat("received_money.value"));
                String[] rowData = {date, value, title, mandobName, id};
                receivedMony.addRow(rowData);
            }
        } catch (Exception e) {
        }    }//GEN-LAST:event_nameCaretUpdate

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        DBcon d = new DBcon();
        try {
            d.con.createStatement();
            d.st.executeUpdate("INSERT INTO `received_money` (`id`, `mandob_id`, `title`, `date`, `value`) VALUES ('" + auto_insert("received_money", "id") + "', '" + cID + "',  '" + name.getText() + "', '" + LocalDate.now() + "','" + -Float.valueOf(val.getText()) + "');");
            float presentage = 0;
            d.rs = d.st.executeQuery("select * from mandob where id = '" + cID + "';");
            d.rs.last();
            float totalRicivedMony = d.rs.getFloat("total_recieved_money");
            float newRecived = -Float.valueOf(val.getText()) + totalRicivedMony;
//            d.st = d.con.createStatement();
//            d.st.executeUpdate("UPDATE mandob set total_recieved_money = '" + newRecived + "' WHERE id = '" + cID + "';");
            d.st = d.con.createStatement();
            d.st.executeUpdate("INSERT INTO `history` (`id`, `person_id`, `person_type`, `date`, `operation`,type) VALUES (NULL, '" + cID + "', '" + this.mandobName.getText() + "', '" + LocalDate.now() + "',  '" + val.getText() + "تسليم المندوب مبلغ قدره  ' , 'mandob');");
            JOptionPane.showMessageDialog(this, "<html><h1 style='font-family: Calibri; font-size:20px;'>تم </h3></html>");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "<html><h1 style='font-family: Calibri; font-size:20px'>هناك خطأ ما -- حاول مرة اخري </h3></html>");
        }
        mandobReceivedItemsTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel87MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel87MouseClicked
        Home.exportExcel(recivedMonyT, "جدول المبالغ المستلمة");
    }//GEN-LAST:event_jLabel87MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel mandobName;
    private javax.swing.JTextField name;
    private javax.swing.JTable recivedMonyT;
    private javax.swing.JTextField val;
    // End of variables declaration//GEN-END:variables
}
