/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Taqseet;

import javax.swing.JTable;

/**
 *
 * @author ahmed
 */
public class select extends javax.swing.JPanel {

    /**
     * Creates new form recieved_items
     */
    public select() {
        initComponents();
        Home.styleTable(new JTable[]{stock_table7});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jLabel99 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        stock_table7 = new javax.swing.JTable();

        setBackground(new java.awt.Color(189, 195, 199));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 60));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 30, 60));

        jPanel2.setBackground(new java.awt.Color(189, 195, 199));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 380));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel79.setText("الكود :");
        add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 100, 60));

        jTextField40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField40.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });
        add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 310, 60));

        jTextField41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(131, 149, 167), 3));
        jTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField41ActionPerformed(evt);
            }
        });
        add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 390, 60));

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel99.setText("الاسم :");
        add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 80, 60));

        jScrollPane9.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        stock_table7.setAutoCreateRowSorter(true);
        stock_table7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stock_table7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1", "1"},
                {"1", "1", "1"},
                {"1", "1", "11"},
                {"11", "11", "11"},
                {"1", "1", "1"},
                {"11", "11", "1"},
                {"1", null, "1"},
                {"1", "1", "1"},
                {null, "1", null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "الملاحظة", "التاريخ", "الكود"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stock_table7.setToolTipText("");
        stock_table7.setGridColor(new java.awt.Color(153, 153, 153));
        stock_table7.setRowHeight(45);
        stock_table7.setRowMargin(3);
        stock_table7.setShowHorizontalLines(true);
        stock_table7.setShowVerticalLines(true);
        stock_table7.setSurrendersFocusOnKeystroke(true);
        jScrollPane9.setViewportView(stock_table7);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 960, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField41ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTable stock_table7;
    // End of variables declaration//GEN-END:variables
}
